env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
extends: 'eslint:recommended'
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-console: off
  no-debugger: off
  no-empty:
    - warn
  no-extra-parens:
    - warn
    - all
    - nestedBinaryExpressions: false
  no-extra-semi: warn
  block-scoped-var: error
  class-methods-use-this: warn
  consistent-return: error
  dot-location:
    - error
    - property
  dot-notation:
    - warn
  no-caller: error
  no-empty-function: warn
  no-eq-null: off
  no-extra-bind: warn
  no-extra-label: warn
  no-floating-decimal: warn
  no-global-assign: error
  no-implicit-coercion: error
  no-invalid-this: off
  no-lone-blocks: warn
  no-multi-spaces: warn
  no-new-wrappers: warn
  no-redeclare: error
  no-self-assign:
    - error
    - props: true
  no-self-compare: error
  no-throw-literal: error
  no-unexpected-multiline: off
  no-unused-expressions:
    - warn
    - allowShortCircuit: true
  no-unused-labels: warn
  no-useless-concat: warn
  no-useless-escape: warn
  no-useless-return: warn
  no-void: error
  no-label-var: error
  no-shadow-restricted-names: error
  no-shadow: warn
  no-undef-init: error
  no-catch-shadow: warn
  no-delete-var: error
  no-undef: error
  no-unused-vars: warn
  global-require: off
  no-path-concat: warn
  prefer-numeric-literals: warn
